### PR TITLE
The Murderbot Diaries by Martha Wells

### PR DESCRIPTION
**Pull request by oschrenk**
If you enjoy  Ann Leckie's Imperial Raadch series or Iain M. Banks' Culture novels, this series of novellas might be for you. They are light, fun to read but yet still engaging enough to get your synapses fired up. 

I wasn’t sure where to put the series, so I followed the (rough) alphabetic structure and put it in the Science Fiction. I also wasn’t sure how to deal with a series. I linked to the first novella and took the average of all 3 released novellas for the rating.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Thanks, @oschrenk! Sounds look a good addition. 

Could you add a list of the books in the series, like we did [here](https://github.com/sindresorhus/awesome-scifi/pull/258/files#diff-0730bb7c2e8f9ea2438b52e419dd86c9L82)? That should be a good template. An average works; I think we've been going with the first book, but your solution works better. Science Fiction is a good category when you're unsure what subgenre to put it in. 

Could you add your name to end of the note, as the rest of the personal reviews also have names that link to GitHub profiles?

**Comment by oschrenk** [comment]
The link was pointing to the diff of this pull request, so I wasn't sure what list of books you were referring to.

I did `--force` pushed some changes:

- linked to series at Goodreads in title
- added a dash after 2017 in title to show that is an ongoing series
- added `Books` with all currently published books
- added my Github handle to the quote

Be aware that this is not an original quote from me. It's a combination of a Tor article and a blurb on the author's page. If that is a problem, please do tell.

**Comment by RichardLitt** [comment]
I pointed to the `Barsoom` series in the diff. Looks like you got the message and added what I was looking for, anyway. :) 

Why don't we add your paragraph above, instead? 

> If you enjoy Ann Leckie's Imperial Raadch series or Iain M. Banks' Culture novels, this series of novellas might be for you. They are light, fun to read but yet still engaging enough to get your synapses fired up.

That sums up what you think about it better, I think. Opinion over synopsis.

**Comment by RichardLitt** [comment]
@oschrenk Ping. :)

**Comment by RichardLitt** [comment]
Added. Thank you, @oschrenk. :)

**Pull request closed without merging**
