### PR TITLE
Merge pull request #1 from sindresorhus/master

### PR DESCRIPTION
**Pull request by augustopedro**
Close #178 PR: Add Star Trek: The Original Series.

### CODE REVIEW

**Comment by RichardLitt** [comment]
What the... I'm confused. What just happened? How can you merge without a file change?

**Comment by augustopedro** [comment]
I don't understand. I just tried to sync my fork with the original, including the PR #178.

**Comment by RichardLitt** [comment]
That is super confusing. Do you have a history of your bash commands? I'd be interested in looking at them! This is weird! :dancers:

**Comment by augustopedro** [comment]
Confusing indeed. I don't have a history of my bash commands because I merged directly from Github. And it's still saying that my fork is 1 commit ahead of the original repository :confused:

**Comment by RichardLitt** [comment]
That's weird.

**Pull request merged**
