### PR TITLE
Complete a trilogy

### PR DESCRIPTION
**Pull request by cp4**

### CODE REVIEW

**Comment by RichardLitt** [comment]
Thanks @cp4. Have you read these two other books? What was your review of them?

**Comment by cp4** [comment]
@RichardLitt Yes, I have read all three books. The interesting thing is, most Chinese readers feel the later two are much better than the first,  with which the Goodreads rating shows no difference. Nevertheless  only the first one got the Hugo Award, so IMO, it's necessary to tell others that don't judge only by award. 

Although each part can be read independently, the whole trilogy has a consistent story line which happens in a very huge time-space context and the first just a beginning. The later two are especially much more hardcore and dramatical, however, gloomy as well, and the pessimism is one main reason for that someone fell very uncomfortable with them.

However, it worth a try for the whole trilogy, don't miss the later two.

**Comment by RichardLitt** [comment]
That's really good to know! Thank you. Would you mind adding that to the commit, as a quote, like we do with the others?

**Comment by cp4** [comment]
OK, I PR again.

**Comment by RichardLitt** [comment]
Awesome! Thank you!

**Pull request merged**
