### PR TITLE
Added links & rating from goodreads

### PR DESCRIPTION
**Pull request by ocombe**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Oh wow. You saved me a lot of work doing that. Thank you! :)

od3vvoq

**Comment by ocombe** [comment]
No prob, I don't have a lot of work to do today (or at least there isn't a lot of work that I want to do today :D)

**Comment by sindresorhus** [comment]
Hah, the best kind of procrastination is productive procrastination :p

You have commit access. Feel free to do other changes directly.

**Comment by ocombe** [comment]
Thanks!

**Pull request merged**
