### PR TITLE
Add Star Trek: Deep Space Nine

### PR DESCRIPTION
**Pull request by augustopedro**

### CODE REVIEW

**Comment by elssar** [comment]
It's not in alphabetical order, needs to go above both the other Start Trek series. And those two aren't in alphabetical order either :/ Could you move those as well?

**Comment by aleksandar-todorovic** [comment]
@elssar I'm going to merge this and arrange them alphabetically in a separate pull request.

**Comment by augustopedro** [comment]
@elssar Done.
@aleksandar-todorovic Sorry, I just saw your comment now.

**Comment by augustopedro** [comment]
Ok, @aleksandar-todorovic. I just saw that you arranged them after I already arranged too. I'm going to delete my branch then. Thanks.

**Pull request merged**
