### PR TITLE
Added better reason why I suggest this

### PR DESCRIPTION
**Pull request by RichardLitt**
See https://github.com/sindresorhus/awesome-scifi/pull/71#discussion_r30949052

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks :)

**Comment by RichardLitt** [comment]
No problem. Officially out of PRs for novels, btw. Will probably think of more later, but can't at the moment.

**Comment by sindresorhus** [comment]
Lol, already?!? :p :nail_care:

**Comment by RichardLitt** [comment]
...Is that a sarcastic emoji? Wow.

**Comment by sindresorhus** [comment]
Lol, that's definitely not the emoji I was going for.

**Pull request merged**
