### PR TITLE
Added Interstellar and Inception to movies list

### PR DESCRIPTION
**Pull request by hiddentao**
Two great sci-fi movies from recent years, IMO.

### CODE REVIEW

**Comment by elssar** [comment]
Could you reverse the order of the movies, to make the order alphabetical?

**Comment by hiddentao** [comment]
The existing list isn't alphabetical. Are you suggesting we make the whole thing alphabetical?

**Comment by elssar** [comment]
Gah! My bad. Too early in the day for me.
Ideally the list should be ordered alphabetically, or by rating, but that should be done in a separate commit.

I'll merge this

**Comment by hiddentao** [comment]
Thanks.

**Pull request merged**
