### PR TITLE
Adding "I, Robot" by Isaac Asimov.

### PR DESCRIPTION
**Pull request by elssar**

### CODE REVIEW

**Comment by RichardLitt** [comment]
Lots of removing errant spaces, but it doesn't really matter. I would add a period after the first rule, and a commentary. Otherwise, lgtm.

**Comment by elssar** [comment]
@RichardLitt oh. I have configured SublimeText to remove trailing spaces, so it automatically removed them.

I was about to add a commentary, but I have a personal task to add commentaries to all me entries, so I figured I would tackle it then(was feeling lazy).

**Comment by RichardLitt** [comment]
Easier to do them one at a time. ;)

**Comment by RichardLitt** [comment]
:+1:

**Pull request merged**
