### PR TITLE
Movie: Stalker (1979)

### PR DESCRIPTION
**Pull request by ggb**
[IMDB](http://www.imdb.com/title/tt0079944/)

> Near a gray and unnamed city is the Zone, an alien place guarded by barbed wire and soldiers. Over his wife's objections, a man rises in the early morning and leaves her with their disabled daughter to meet two men. He's a Stalker, one of a handful who have the mental gifts (and who risk imprisonment) to lead people into the Zone to the Room, a place where one's secret hopes come true.

### CODE REVIEW

**Comment by kevva** [comment]
Make sure you adhere to the [contribution guidelines](https://github.com/sindresorhus/awesome-scifi/blob/master/contributing.md).

**Comment by ggb** [comment]
Oh sorry, I missed the alphabetical order-thing. I'll fix that!

**Comment by kevva** [comment]
And your commentary.

**Comment by ggb** [comment]
I've added both.

**Comment by aleksandar-todorovic** [comment]
I'm so sorry to bother you even further now, but when you add a commentary to this repository, you should sign your commentary like this:

```gfm
Some random comment that explains why is the thing I'm submitting awesome and why the rest of you should read / watch it. - [@aleksandar-todorovic](https://github.com/aleksandar-todorovic)
```

**Comment by ggb** [comment]
Thanks Aleksandar, I've added that, too.

**Comment by aleksandar-todorovic** [comment]
Thank you for your contribution!

**Pull request merged**
