### PR TITLE
Added Aurora Cycle series

### PR DESCRIPTION
**Pull request by sammy4gh**
Added Aurora Cycle series to Military section

### CODE REVIEW

**Comment by sammy4gh** [comment]
What makes this novel awesome is the build up to the final epic battle. It starts as a small team of ragtags who were framed for a crime and later find out that the least of their  worry  is the intergalactic military but rather  an incomprehensible galaxy ending force whose sole existence is to added all living things to its hive.

**Comment by RichardLitt** [comment]
Cool. Can you add that to the commit?

**Comment by sammy4gh** [comment]
I have added details on what makes this novel awesome

**Comment by RichardLitt** [comment]
Thanks!

**Pull request merged**
