### PR TITLE
Added the original 'Solaris' film

### PR DESCRIPTION
**Pull request by RichardLitt**

### CODE REVIEW

**Comment by RichardLitt** [comment]
The original film is awesome, but isn't on this list. I added the year after the title, seemed to make sense. We might want to add a field for director, too.

**Comment by sindresorhus** [comment]
:+1:

**Comment by sindresorhus** [comment]
How do you think the director should be notated? Maybe like we do with author for books.

**Comment by RichardLitt** [comment]
That might work. 

#### [Solaris]() (2002) Director: Steven Soderbergh [4.5]

Seems like a lot. Maybe:

#### [Solaris]() (2002) [4.5]
Director: _Steven Soderbergh_

And we can use that for other differentiators, too.

**Comment by sindresorhus** [comment]
I prefer the latter.

**Pull request merged**
