### PR TITLE
Added 'The Island of Dr. Death And Other Stories and Other Stories

### PR DESCRIPTION
**Pull request by RichardLitt**
Commentary speaks for itself.

### CODE REVIEW

**Comment by elssar** [comment]
First published date missing

**Comment by RichardLitt** [comment]
Huh. Apparently:

```sh
$ git add -A
$ git commit --amend
$ git push -f origin HEAD
$ git checkout master
$ git rebase -
$ git pull
$ git push upstream master
```
Will add a lot of junk to the commit logs. @sindresorhus Any idea why?

**Comment by sindresorhus** [comment]
`git pull` => `git pull --rebase`

**Comment by RichardLitt** [comment]
Huh. Did not know that. Thanks.

**Pull request merged**
