### PR TITLE
Adding 'Nexus' to hard Sci-Fi. 🔬📖

### PR DESCRIPTION
**Pull request by christianboyle**
Adding 'Nexus' to hard Sci-Fi. 🔬📖

### CODE REVIEW

**Comment by mihailim** [comment]
Interesting!

I'd propose two changes, though:

- Rounding the rating number to a single digit, as per contribution guidelines
- Including the entire Goodreads description instead of just the first paragraph; more text is perfectly okay, and in fact makes the entry look better :)

**Comment by mihailim** [comment]
Thanks! LGTM.

**Comment by christianboyle** [comment]
Good catches, that's what I get for coding before coffee.

**Comment by aleksandar-todorovic** [comment]
Looks like we're all set. Thanks for the Pull Request!

**Comment by mihailim** [comment]
Thanks!

**Comment by christianboyle** [comment]
Thanks gents.

**Pull request merged**
