### PR TITLE
Adds Children of Men

### PR DESCRIPTION
**Pull request by aleksandar-todorovic**

### CODE REVIEW

**Comment by RichardLitt** [comment]
Needs the IMDB description. Otherwise, this truly belongs here.

**Comment by RichardLitt** [comment]
This is the text needed: `In 2027, in a chaotic world in which women have become somehow infertile, a former activist agrees to help transport a miraculously pregnant woman to a sanctuary at sea.`

**Comment by aleksandar-todorovic** [comment]
It's fixed now!

**Comment by RichardLitt** [comment]
Beauty.

**Pull request merged**
