### PR TITLE
Add House of Leaves

### PR DESCRIPTION
**Pull request by thedeany**
I can't say I've ever been "excited" to read a book, but after hearing about _House of Leaves_ I was undeniably excited. I was in the middle of another book when my wife surprised me with this one, and I finished the book I was already reading much more quickly than I normally would have just so I could start reading _House of Leaves_.

If you're looking for a book which lays out all the answers for you and packages things up neatly with a bow, this is not for you 😄

---

This book is widely considered "horror" as well but I wasn't sure if a new "Horror" subsection should be created, so I put the entry in the general "Science Fiction" section. If you'd like a "Horror" subsection created as part of this PR, let me know and I can add it and move _House of Leaves_ there!

### CODE REVIEW

**Comment by RichardLitt** [comment]
I think this is a great addition. And yeah, why not create a horror section? :)

**Comment by thedeany** [comment]
Awesome, I’ll make the change later today!

**Comment by thedeany** [comment]
@RichardLitt I have added the Horror section! Let me know if there are any other changes I need to make.

**Comment by RichardLitt** [comment]
Looks good to me! Thanks!

**Pull request merged**
