### PR TITLE
Add Person of Interest to TV Shows

### PR DESCRIPTION
**Pull request by AB1908**
Person of Interest being my favorite sci-fi show, I simply had to recommend it.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Thank you!

**Comment by AB1908** [comment]
You're welcome, but why? 😅

**Comment by RichardLitt** [comment]
For submitting a PR and adding to this list! :D

**Comment by AB1908** [comment]
Of course! You do need to watch this though.

**Pull request merged**
