### PR TITLE
Add Oblivion (2013)

### PR DESCRIPTION
**Pull request by icyflame**

### CODE REVIEW

**Comment by elssar** [comment]
Commentary is more of a description.

**Comment by icyflame** [comment]
@elssar Yes, I agree! It was a bit chatty! I have changed it, reduced it.

**Comment by aleksandar-todorovic** [comment]
Thank you! The description seems good now. I'm going to merge this and I'm looking forward to seeing the movie because of your description.

**Comment by icyflame** [comment]
Thanks, yo!

**Pull request merged**
