### PR TITLE
Add Electric Dreams

### PR DESCRIPTION
**Pull request by siriuzwhite**
Each episode of the series is based on a short story by Philip K. Dick

### CODE REVIEW

**Comment by RichardLitt** [comment]
Nice, hadn't heard of this. Can you add a short note why you think it is awesome?

**Comment by siriuzwhite** [comment]
I mean they are based on short stories by PKD, isn't that awesome enough?

**Comment by RichardLitt** [comment]
Take a look at the Contributing guide. https://github.com/sindresorhus/awesome-scifi/blob/master/contributing.md

**Comment by sindresorhus** [comment]
Ping

**Pull request closed without merging**
