### PR TITLE
Added the CS Lewis Space trilogy

### PR DESCRIPTION
**Pull request by RichardLitt**
These books stand alone, but should probably be put together. How are we doing that, in this list? I just added them all. Also, I added a new section for them, because none of the others felt right.

### CODE REVIEW

**Comment by elssar** [comment]
- Nav link to the new category does not work.
 - Not sure whether a new category is needed.
 - Should probably merge the three books into one entry.

**Comment by RichardLitt** [comment]
Fixed the link. I'd say a new category is needed, these are made intentionally to talk about theology, and less to talk about hard science fiction. 

As for the merge, I don't know. They're all very different in character. _That Hideous Strength_ is totally different than _Out of the Silent Planet_.

**Comment by elssar** [comment]
How many books can be categorized as theological over other categories? Not sure.

Unless the books in the series can stand alone, I think they should be merged. Precedent has already been established for merging. Check "Culture Series" and "Commonwealth Saga". The latter is actually two different series set in the same universe, but very different from each other(but with a lot of common characters).

**Comment by RichardLitt** [comment]
The same goes for Drama, Biopunk, and Police Procedural Fiction. Maybe we should remove all one-item categories, and put everything in science fiction until people want to pull them out.

**Comment by RichardLitt** [comment]
How do we feel about this? I think it's a more elegant solution than merging them into one. There is a Goodreads link for the series, but no description; merging them would make the commentary a bit odd, as I have a different comment for each book. I think this is a good compromise.

**Comment by sindresorhus** [comment]
Looks good to me.

**Comment by RichardLitt** [comment]
huh. Did not mean tot close that.

**Comment by arthurvr** [comment]
@RichardLitt Why would you reopen it? It's merged so the PR should be closed isn't it?

**Comment by sindresorhus** [comment]
@RichardLitt I squashed and merged it for you ;)

**Comment by RichardLitt** [comment]
@sindresorhus whoa. How did you do that without leaving a message saying you did it? And it says I have unmerged commits. I've not seen this before - could you explain how that worked? Seems nifty.

**Comment by sindresorhus** [comment]
I just pulled in your PR locally, squashed the commits, changed the author to you again, added a `closes #44` to the commit message and pushed.

**Comment by RichardLitt** [comment]
How did you change the author, though? manually?

**Comment by sindresorhus** [comment]
I have a git alias in my global .gitconfig:

```ini
credit = !sh -c 'git commit --amend --author \"$1\" -C HEAD' -
```

Then just:

```sh
git credit richard
```

**Comment by RichardLitt** [comment]
Whoa. Sweet. Thanks.

**Pull request closed without merging**
