### PR TITLE
Added Barsoom (John Carter) series

### PR DESCRIPTION
**Pull request by uraimo**

### CODE REVIEW

**Comment by RichardLitt** [comment]
I would add the titles of the series. See how we did it for [CS Lewis's](https://github.com/sindresorhus/awesome-scifi#space-trilogy-out-of-the-silent-planet-perelandra-and-that-hideous-strength-by-c-s-lewis-41).

**Comment by uraimo** [comment]
Ok for me, we should maybe select just the best of the series (10-11 books total) but i'll need help from  someone that has read them recently to select the best ones :)

**Comment by RichardLitt** [comment]
Hmm. That's a lot. @sindresorhus Would you be cool with listing individual titles? See how I did it in [Awesome-Fantasy](https://github.com/RichardLitt/awesome-fantasy#earthsea-by-ursula-k-le-guin).

**Comment by sindresorhus** [comment]
👍

**Comment by RichardLitt** [comment]
Yeah! Ok, cool. Thanks @uraimo, working through new territory for this list. <3

**Pull request merged**
