### PR TITLE
Add the Expanse series by James S. A. Corey

### PR DESCRIPTION
**Pull request by jpkempf**
See #110

### CODE REVIEW

**Comment by jpkempf** [comment]
See #110

**Comment by RichardLitt** [comment]
This looks good to me. I think this is the right way to deal with larger series. 

@sindresorhus, look fine to you?

**Comment by sindresorhus** [comment]
Sure, but if not too much to ask I would have loved to see a couple of sentences of what @jpkempf thought of the book. Did you enjoy it? Anything you didn't like?

**Comment by RichardLitt** [comment]
"I liked it quite a bit. Great writing as usual." would also be acceptable, doesn't have to be the highest of accolades. :)

**Comment by jpkempf** [comment]
@RichardLitt @sindresorhus There, that should do it, i hope. :)

**Comment by sindresorhus** [comment]
Perfect. Thank you :) Happy holidays! 🎄

**Pull request closed without merging**
