### PR TITLE
Added 'Star Trek II: The Wrath of Khan'

### PR DESCRIPTION
**Pull request by RichardLitt**
First entry for #45

### CODE REVIEW

**Comment by hiddentao** [comment]
Awesome. To make it more beautiful and in-line with the other entries I think the synopsis should come first, followed by the commentary. And the commentary should be _italicised_. What do you think?

**Comment by RichardLitt** [comment]
Hmm, I disagree. None of the other entries have the synopsis first; I think that synopsis should come after the commentary, as the synopsis is easy to get from other sources and isn't as important as why it is on this list. Italics are currently being used to describe section headers, and I think given that the synopsis is in quotes and the title is bolded, adding italics isn't necessary to differentiate the text. 

What do you think?

**Comment by hiddentao** [comment]
My thinking was: first I want to know what it is, and then I want to know why I should watch it. The synopsis is shorter to read too, so I feel like it's only a small delay before I read onto the _why_ - and better yet I have an idea of what the movie is about before I read the _why_.

As for italics, that was a minor point - non-italics is fine with me.

**Comment by RichardLitt** [comment]
Normally, the synopsis should be longer - it is for all of the books. And I'm not sure - I want to know why I should read a book before reading synopses, mostly because I think most synopses aren't good at all. I want to know why a book is on this list, not what it is in general. 

Maybe this should be a wider discussion in an issue, as the ramifications of your suggestion are more far-reaching than this PR.

**Comment by RichardLitt** [comment]
Added my name to the commentary.

**Comment by hiddentao** [comment]
@sindresorhus Your thoughts on synopsis/commentary order?

**Comment by RichardLitt** [comment]
@elssar Can you wait for @sindresorhus to respond, as he was asked? Kind of undercuts the conversation a bit. 

@hiddentao - I encourage you to open an issue about order, although I disagree with you. :)

**Comment by elssar** [comment]
@RichardLitt synopsis/commentary order is something that would have to be dealt with in a separate pull request. If we decide to switch the order, it can(and IMO should) be done for all entries in one PR - so that things are uniform.

**Comment by RichardLitt** [comment]
@elssar Agreed. Just seemed like it was a bit of a 'conversation over' pull. :) No worries, we'll discuss in #50.  Thanks for accepting the PR.

**Pull request merged**
