### PR TITLE
Adding 'Hackers' to movies. 💾📟

### PR DESCRIPTION
**Pull request by christianboyle**
Adding 'Hackers' to movies. 💾📟

### CODE REVIEW

**Comment by aleksandar-todorovic** [comment]
It's funny how the point of this movie was to create a realistic scenario (at least I think so), and now it fits the Science Fiction section perfectly (in my opinion).

I'm going to wait for some other opinion before I merge this because it might not be considered as a SciFi movie to someone.

**Comment by christianboyle** [comment]
MGM classifies it as ["science fiction thriller"](http://en.wikipedia.org/wiki/Hackers_%28film%29).

**Comment by aleksandar-todorovic** [comment]
In that case I'm gonna go ahead and accept this submission. Thanks for the Pull Request!

**Comment by christianboyle** [comment]
Thanks sir.

**Pull request merged**
