### PR TITLE
Fix spelling of "grammar"

### PR DESCRIPTION
**Pull request by squarejaw**

### CODE REVIEW

**Comment by mihailim** [comment]
:D

Thanks!

**Comment by sindresorhus** [comment]
It was intentional. Meant as an obvious joke :p

**Comment by mihailim** [comment]
... o.O

Well, _that_ backfired... Serves me right for looking at stuff at midnight... Should I revert?

**Comment by squarejaw** [comment]
Heh, figured it might be a joke. :wink:

**Comment by sindresorhus** [comment]
Nah

**Comment by mihailim** [comment]
def further_strategy(self):
        self.brain.disengage()  # Glucose drain and apparently wasn't being used anyway
        self.proximity_locator(class='hole').crawl_into()

**Pull request merged**
